import { Wine } from "./types";

export const wines: Wine[] = [
  {
    id: "riesling-2023",
    nazev: "Ryzlink rýnský",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 210,
    popis:
      "Minerální a svěží víno s tóny lipového květu, akátu, citrusů a přezrálých kdoulí.",
    chut: "Šťavnatá meruňka, citrusy.",
    vune: "Bílé květy, limetová kůra, medové tóny.",
    pairing: "Hodí se k tuňáku, krabímu salátu nebo býlím masům.",
    parametry: { cukr: "0,1 g/l", kyseliny: "5,4 g/l", alkohol: "12,5 % obj." },
    obrazek: "/neuburk.jpg",
    vyber: true,
  },
  {
    id: "vltavin-2022",
    nazev: "Veltlínské zelené",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Pálava, Jižní Morava",
    cena: 210,
    popis:
      "Moravská klasika s pikantním pepřovým závěrem, citrusy, tóny lipový květ, bílý rybíz i mandle s minerální linkou.",
    chut: "Citrusy, jemný bílý pepř mandlová a minerální linka.",
    vune: "Broskev, lipový květ a lehká bylinná stopa.",
    pairing: "Kuřecí maso, ryby, drůbež i zelenina.",
    parametry: { cukr: "0,5 g/l", kyseliny: "4,4 g/l", alkohol: "12,5 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "chardonnay-2024",
    nazev: "Chardonnay",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 230,
    popis:
      "Elegantní, minerální Chardonnay s tóny hrušky, banánu, kdoulí a citrusů, med květu akátu, na patře karamelová chuť. Skvěle dopní krémová risotta či mořské plody.",
    chut: "Svěží, ovocná chuť.",
    vune: "Svěžest čerstvosti.",
    pairing: "Letní saláty, paella, čerstvé těstoviny s pestem.",
    parametry: { cukr: "0,5 g/l", kyseliny: "4,9 g/l", alkohol: "14 % obj." },
    obrazek: "/neuburk.jpg",
    vyber: true,
  },
  {
    id: "csavilon-PIWI-2024",
    nazev: "Savilon PIWI",
    rocnik: 2021,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulov",
    cena: 210,
    popis:
      "Plné, harmonické víno s vůní broskví a jemnými květinovými tóny, květ černého bezu, grapefruil, pomelo. Ideální k pokrmům z ryb a jemných mas.",
    chut: "Pečené jablko, vanilka, lehký toast, dlouhá perzistence.",
    vune: "Máslová brioška, lískové oříšky, sušený ananas.",
    pairing: "Krémové risotto, mořské plody.",
    parametry: { cukr: "1,4 g/l", kyseliny: "5,6 g/l", alkohol: "15 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "muskat-2024",
    nazev: "Muškát moravský",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Moravské zemské víno",
    vinarsvi: "Mayer Mikulov",
    oblast: "Pálava, Jižní Morava",
    cena: 210,
    popis:
      "Aromatické víno s tóny muškátových květů, broskví a hroznů. Výborné jako aperitiv či k lehkým letním pokrmům.",
    chut: "Med a meruňky, lehká kořenitost, hebký závěr.",
    vune: "Květ akátu, muškát, kandované ovoce.",
    pairing: "Aperitiv či lehké letní pokrmy.",
    parametry: { cukr: "4,2 g/l", kyseliny: "4,7 g/l", alkohol: "11,5 % obj." },
    obrazek: "/neuburk.jpg",
    vyber: true,
  },
  {
    id: "zweigelt-2024",
    nazev: "Zweigeltrebe - červené",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr - lehce barykové",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 230,
    popis: "Ovocné víno s tóny třešní, malin, ostružiny, višně, pecky z višní.",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: { cukr: "0,2 g/l", kyseliny: "4,1 g/l", alkohol: "13,5 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "alibernet-2024",
    nazev: "Alibernet - červené",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 250,
    popis:
      "Intenzivní víno s černým rybízem, ostružinami a kořenitými tóny, hořká čokoláda, švestky. Plné tělo a výrazné taniny - ideální ke steakům či jehněčímu.",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: { cukr: "0,3 g/l", kyseliny: "5,2 g/l", alkohol: "11 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "merlot-2024",
    nazev: "Merlot - červené",
    rocnik: 2024,
    zatrideni2: "Suché víno",
    zatrideni: "Pozdní sběr - lehce barykové",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 250,
    popis:
      "Hladké, vyvážené víno s tóny černé třešně, pecky z černých třešní svěstek, ostružin, koření a černé hořké čokolády. Znalci objevují kouzlo přezrálých fíků. Hodí se ke grilovanému hovězímu či kachně",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: { cukr: "2,6 g/l", kyseliny: "4,6 g/l", alkohol: "13 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "souvignier-gris-2024",
    nazev: "Souvignier gris",
    rocnik: 2024,
    zatrideni2: "Polosuché víno",
    zatrideni: "Výběr z hroznů",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 230,
    popis:
      "Ovocité víno (zelené jablko, meruňky, broskve, grapefruit, medovina přezrálá hruška, přezrálý červené pomeranč) z pečlivě vybraných hroznů.",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: { cukr: "11,9 g/l", kyseliny: "6,2 g/l", alkohol: "14 % obj." },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "rose-zw-2024",
    nazev: "Rosé Zweigetrebe",
    rocnik: 2024,
    zatrideni2: "Polosladké víno",
    zatrideni: "Pozdní sběr",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 230,
    popis:
      "Svěží rosé s tóny jahod a malin, povidla, přezrálé svěstky, pecky ze švestek, možno i černý rybíz. Osvěžující, ideální k letním jídlům.",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: {
      cukr: "21,2 g/l",
      kyseliny: "4,8 g/l",
      alkohol: "11,5 % obj.",
    },
    obrazek: "/neuburk.jpg",
  },
  {
    id: "tc-2024",
    nazev: "Turold Cuvée",
    rocnik: 2024,
    zatrideni2: "Polosladké víno",
    zatrideni: "Moravské zemské víno",
    vinarsvi: "Mayer Mikulov",
    oblast: "Mikulovsko, Jižní Morava",
    cena: 210,
    popis:
      "Komplexní víno s citrusovými chuti, přezrálé hrušky a minerální tóny, elegantní a svěží.",
    chut: "Tmavé třešně, ostružiny, jemná čokoláda v závěru.",
    vune: "Švestková povidla, koření, lehká kouřovost.",
    pairing: "Zvěřina, hovězí steak, pečené žampiony, tvrdé sýry.",
    parametry: { cukr: "23 g/l", kyseliny: "5,1 g/l", alkohol: "12,5 % obj." },
    obrazek: "/neuburk.jpg",
  },
];

export const featuredWines = wines.filter((wine) => wine.vyber).slice(0, 3);

export const getWineById = (id: string) => wines.find((wine) => wine.id === id);
